### ISSUE TITLE
Doesn't build on Linux Mint 22.3

### ISSUE THREAD

**Issue by freq-mod** [ares-emulator/ares#2576]
**Describe the bug**
```In file included from /home/anon/ares/ruby/ruby.cpp:32:
/home/anon/ares/ruby/audio/audio.cpp:3:10: fatal error: SDL3/SDL.h: No such file or catalogue.
    3 | #include <SDL3/SDL.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

**To Reproduce**
1. git pull
2. git submodule update
3. See error

**Expected behavior**
It should build fine. SDL3 isn't installable in Linux Mint via package manager so libsdl3-dev isnt an option to me

**Comment by remutro** [comment]
We've made the decision to only use SDL3 for audio & input going forward. As a small team we can't support a dozen+ audio backends and a bunch of different input drivers all with different issues. We want to focus on supporting one of them and fixing known problems within one driver. SDL3 is the standard at this point. It is very easy to clone the SDL3 repo and build it, and you could probably get away with downloading Ubuntu based SDL3 debian packages.

**Comment by freq-mod** [comment]
I compiled and installed SDL3, then i did make clean. That error is gone but it still doesnt compile, build fails at linking stage
```
100%] Linking CXX executable ares
/usr/bin/ld: /tmp/ccEXcwux.ltrans2.ltrans.o: in function `nall::main(nall::Arguments)':
/home/anon/ares/ruby/audio/audio.cpp:8:(.text.startup+0x7529): undefined reference to `SDL_SetHint'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:99:(.text.startup+0x759a): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /tmp/ccEXcwux.ltrans4.ltrans.o: in function `std::_Function_handler<void (), InputManager::createHotkeys()::{lambda()#5}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.0]':
/home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x4799): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /tmp/ccEXcwux.ltrans4.ltrans.o: in function `std::_Function_handler<void (), InputManager::createHotkeys()::{lambda()#6}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.0]':
/home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x4b38): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /tmp/ccEXcwux.ltrans4.ltrans.o: in function `std::_Function_handler<void (), InputManager::createHotkeys()::{lambda()#7}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.0]':
/home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x4e5d): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x4e88): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /tmp/ccEXcwux.ltrans14.ltrans.o: in function `Program::audio(std::shared_ptr<ares::Core::Audio::Stream>)':
/home/anon/ares/ruby/audio/audio.cpp:120:(.text+0xb14): undefined reference to `SDL_PutAudioStreamData'
/usr/bin/ld: /tmp/ccEXcwux.ltrans14.ltrans.o:/home/anon/ares/ruby/audio/audio.cpp:106:(.text+0xbc3): undefined reference to `SDL_GetAudioStreamQueued'
/usr/bin/ld: /tmp/ccEXcwux.ltrans14.ltrans.o: in function `Program::unload()':
/home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x7030): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /tmp/ccEXcwux.ltrans14.ltrans.o: in function `Program::emulatorRunLoop(unsigned long)':
/home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x849e): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x8688): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /tmp/ccEXcwux.ltrans14.ltrans.o: in function `Program::event(ares::Event)':
/home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x91d8): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x91e8): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /tmp/ccEXcwux.ltrans14.ltrans.o:/home/anon/ares/ruby/audio/audio.cpp:99: more undefined references to `SDL_ClearAudioStream' follow
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `InputSDL::~InputSDL() [clone .lto_priv.0]':
/home/anon/ares/ruby/input/joypad/sdl.cpp:80:(.text+0x3c81): undefined reference to `SDL_CloseJoystick'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o:/home/anon/ares/ruby/input/joypad/sdl.cpp:83:(.text+0x3d3e): undefined reference to `SDL_QuitSubSystem'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `InputSDL::rumble(unsigned long, unsigned short, unsigned short)':
/home/anon/ares/ruby/input/joypad/sdl.cpp:62:(.text+0x4289): undefined reference to `SDL_RumbleJoystick'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `InputJoypadSDL::enumerate()':
/home/anon/ares/ruby/input/joypad/sdl.cpp:93:(.text+0x99c9): undefined reference to `SDL_CloseJoystick'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:97:(.text+0x9a2e): undefined reference to `SDL_GetJoysticks'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:105:(.text+0x9e64): undefined reference to `SDL_OpenJoystick'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:112:(.text+0x9e8a): undefined reference to `SDL_GetNumJoystickAxes'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:113:(.text+0x9e9b): undefined reference to `SDL_GetNumJoystickHats'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:114:(.text+0x9eaf): undefined reference to `SDL_GetNumJoystickButtons'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:116:(.text+0x9ece): undefined reference to `SDL_GetError'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:161:(.text+0xa15c): undefined reference to `SDL_free'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:162:(.text+0xa161): undefined reference to `SDL_UpdateJoysticks'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:121:(.text+0xa390): undefined reference to `SDL_GetJoystickVendorForID'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:122:(.text+0xa39d): undefined reference to `SDL_GetJoystickProductForID'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:127:(.text+0xa3cb): undefined reference to `SDL_GetJoystickGUIDForID'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:129:(.text+0xa3fc): undefined reference to `SDL_GUIDToString'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:107:(.text+0xa6d0): undefined reference to `SDL_GetError'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:144:(.text+0xaa37): undefined reference to `SDL_GetJoystickName'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:146:(.text+0xaa8d): undefined reference to `SDL_GetJoystickPlayerIndex'
/usr/bin/ld: /home/anon/ares/ruby/input/joypad/sdl.cpp:147:(.text+0xb318): undefined reference to `SDL_GetJoystickID'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `InputSDL::poll()':
/home/anon/ares/ruby/input/joypad/sdl.cpp:31:(.text+0xc420): undefined reference to `SDL_UpdateJoysticks'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o:/home/anon/ares/ruby/input/joypad/sdl.cpp:33:(.text+0xc44c): undefined reference to `SDL_PollEvent'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o:/home/anon/ares/ruby/input/joypad/sdl.cpp:41:(.text+0xc51d): undefined reference to `SDL_GetJoystickAxis'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o:/home/anon/ares/ruby/input/joypad/sdl.cpp:45:(.text+0xc752): undefined reference to `SDL_GetJoystickHat'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o:/home/anon/ares/ruby/input/joypad/sdl.cpp:51:(.text+0xca5f): undefined reference to `SDL_GetJoystickButton'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `InputSDL::initialize()':
/home/anon/ares/ruby/input/joypad/sdl.cpp:80:(.text+0xd029): undefined reference to `SDL_CloseJoystick'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o:/home/anon/ares/ruby/input/joypad/sdl.cpp:83:(.text+0xd0ed): undefined reference to `SDL_QuitSubSystem'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `InputSDL::initialize()':
/home/anon/ares/ruby/input/joypad/sdl.cpp:80:(.text+0xd169): undefined reference to `SDL_CloseJoystick'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o:/home/anon/ares/ruby/input/joypad/sdl.cpp:83:(.text+0xd1c9): undefined reference to `SDL_QuitSubSystem'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `InputSDL::initialize()':
/home/anon/ares/ruby/input/joypad/sdl.cpp:71:(.text+0xd1d3): undefined reference to `SDL_Init'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o:/home/anon/ares/ruby/input/joypad/sdl.cpp:72:(.text+0xd1dd): undefined reference to `SDL_InitSubSystem'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `InputSDL::create()':
/home/anon/ares/ruby/input/sdl.cpp:25:(.text+0xd2a7): undefined reference to `SDL_SetHint'
/usr/bin/ld: /tmp/ccEXcwux.ltrans22.ltrans.o: in function `ruby::Audio::terminate()':
/home/anon/ares/ruby/audio/audio.cpp:184:(.text+0x10245): undefined reference to `SDL_DestroyAudioStream'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:193:(.text+0x1025f): undefined reference to `SDL_WasInit'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:187:(.text+0x10278): undefined reference to `SDL_CloseAudioDevice'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:194:(.text+0x10287): undefined reference to `SDL_QuitSubSystem'
/usr/bin/ld: /tmp/ccEXcwux.ltrans122.ltrans.o: in function `ruby::Audio::hasDevices() [clone .constprop.0]':
/home/anon/ares/ruby/audio/audio.cpp:16:(.text+0x286e): undefined reference to `SDL_GetAudioPlaybackDevices'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:18:(.text+0x2886): undefined reference to `SDL_GetAudioDeviceName'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:20:(.text+0x29e4): undefined reference to `SDL_free'
/usr/bin/ld: /tmp/ccEXcwux.ltrans122.ltrans.o: in function `Program::audioDeviceUpdate() [clone .constprop.0]':
/home/anon/ares/ruby/audio/audio.cpp:8:(.text+0x2fc6): undefined reference to `SDL_SetHint'
/usr/bin/ld: /tmp/ccEXcwux.ltrans122.ltrans.o: in function `Program::pause(bool) [clone .constprop.0]':
/home/anon/ares/ruby/audio/audio.cpp:99:(.text+0x4408): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /tmp/ccEXcwux.ltrans123.ltrans.o: in function `ruby::Audio::initialize() [clone .constprop.0] [clone .isra.0]':
/home/anon/ares/ruby/audio/audio.cpp:135:(.text+0xdc22): undefined reference to `SDL_InitSubSystem'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:144:(.text+0xdd61): undefined reference to `SDL_SetHint'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:158:(.text+0xdda9): undefined reference to `SDL_OpenAudioDeviceStream'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:161:(.text+0xddbd): undefined reference to `SDL_GetAudioStreamDevice'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:164:(.text+0xddfb): undefined reference to `SDL_ResumeAudioDevice'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:99:(.text+0xde5f): undefined reference to `SDL_ClearAudioStream'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:151:(.text+0xde7e): undefined reference to `SDL_GetAudioPlaybackDevices'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:153:(.text+0xdea5): undefined reference to `SDL_GetAudioDeviceName'
/usr/bin/ld: /home/anon/ares/ruby/audio/audio.cpp:155:(.text+0xdedf): undefined reference to `SDL_free'
collect2: error: ld returned 1 exit status
make[2]: *** [desktop-ui/CMakeFiles/desktop-ui.dir/build.make:266: desktop-ui/ares] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:1186: desktop-ui/CMakeFiles/desktop-ui.dir/all] Błąd 2
make: *** [Makefile:136: all] Błąd 2
```

**Comment by remutro** [comment]
Did you run the install command after building SDL3? Command looks something like this, all the install path may need to be changed if they usually go somewhere else for your distro:

`sudo cmake --install build --prefix /usr/local`

**Comment by freq-mod** [comment]
I ran `sudo make install`, I can try the above tomorrow

**Comment by XerTheSquirrel** [comment]
You would likely be better off building and installing it the Debian way, that is:

 * Download the source dsc, src tgz, and sig from the Ubuntu, or Debian, repository.
 * `dpkg-buildpackage`, install dependencies as missing, debug, etc.
 * Then `dpkg -i` the binary debs that came out of it.

This may get you a more proper SDL3 setup due to arch specific prefixes and whatnot.

**Comment by remutro** [comment]
These commands work for Ubuntu 24.04 LTS, which I think latest Mint is based off of?

```
git clone https://github.com/libsdl-org/SDL.git
cd SDL && mkdir build
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release
sudo cmake --install build --prefix=/usr/local
```

**Comment by freq-mod** [comment]
@remutro @XerTheSquirrel none of your advices helped. Still the same error in linking. even after make clean
